<div style="width:99%; margin:1px auto; border: #006600" >
  <div class="titleform">
    <h1>Búsqueda de Pacientes</h1>   
  </div>
</div>
<div  id ="divManual" style="width:99%;height:99%;margin-left:1%;margin-right:1%;overflow:scroll; ">

Para consultar los datos del paciente se tienen varias opciones: Por apellidos, nombres, c&oacute;digo, DNI o por la combinaci&oacute;n de estos datos.<br><br><a href="#DNI">*B&uacute;squeda por DNI o c&oacute;digo</a><br><a name="Apellido" id="Apellido"></a><br><b>Ejemplo 1:</b> <i>B&uacute;squeda por apellido</i><br><br>Para el caso de nombres y apellidos son datos que pueden repetirse en varios pacientes, se tendr&aacute;n varias filas como resultado de la b&uacute;squeda; primero se escribe el dato o datos por los que se desea hacer la b&uacute;squeda, en este caso el apellido paterno.<br><br><div align="center"><img src="../../../imagen/ayuda/imgBuscaPct1.png" alt="" width="72%"></div><br><br><b>Observaci&oacute;n:</b>Para este caso una vez ingresado el apellido paterno presionar la tecla ENTER y autom&aacute;ticamente se realizar&aacute; la busqueda y adem&aacute;s el cursor se ubicar&aacute; en el siguiente campo, lo mismo ocurre para el caso del apellido materno (Ape. Mat:) y el nombre (Nombre:)<br><br>Luego se pulsa el bot&oacute;n buscar, se muestran las coincidencias en la tabla que se encuetra debajo del cuadro de b&uacute;squeda, una vez mostrada la lista se selecciona la fila deseada (tomar&aacute; un color naranja).<br><i>*<b>Nota:</b> Las filas rojas indican que no se han registrado todos los datos del paciente.</i><br><br><div align="center"><img src="../../../imagen/ayuda/imgBuscaPct2.png" alt="" width="85%"></div><br><br>Una vez seleccinada la fila se mostrar&aacute; los datos del paciente elegido.<br><br><div align="center"><img src="../../../imagen/ayuda/imgBuscaPct3.png" alt="" width="92%"></div><br><a name="DNI" id="DNI"></a><br><a href="#Apellido">*B&uacute;squeda por nombre y/o apellidos</a><br><br><b>Ejemplo 2:</b> <i>B&uacute;squeda por DNI</i><br><br>Para el caso de datos &uacute;nicos como el documento de identidad o el c&oacute;digo de paciente, se tendr&aacute; una sola fila como resultado de la b&uacute;squeda; similar al caso anterior se escribe el n&uacute;mero por el cual se desea hacer la b&uacute;squeda, en este caso el DNI.<br><br><div align="center"><img src="../../../imagen/ayuda/imgBuscaPct4.png" alt="" width="98%"></div><br><br>Luego presione la tecla ENTER o pulse el bot&oacute;n buscar, luego se visualizar&aacute; el resultado de la b&uacute;squeda en la tabla que se encuentra debajo del cuadro de b&uacute;squeda, y en el lado derecho se visualizar&aacute; los datos detallados del paciente autom&aacute;ticamente.

</div>


